### PR TITLE
Update the chrome extension to fix the CRX_HEADER_INVALID error

### PR DESCRIPTION
**Pull request by kirkegaard**
Packed a new Chrome extension since it wouldnt load correctly :)

### CODE REVIEW

**Comment by mikker** [comment]
Is this just a rebuild of the existing code? How do I know? (I trust you of course but I suppose this is not something I could be sure of?)

And btw, wouldn't you like to try the new [Joof.app](https://joof.app) Mac version and Chrome extension instead?

**Comment by kirkegaard** [comment]
Yes it's just a rebuild of the existing code. I just packed a new extension. Pinky swear!
And YES! Would love to give it a try 👯‍♂️

**Comment by kirkegaard** [comment]
Also, if you wanna make sure, just unzip the crx file. Its just a regular zip file :)

**Comment by mikker** [comment]
💙💚💛💜❤️

**Pull request merged**
